import { SEOHead } from '@/components/shared/SEOHead';
import { Footer } from '@/components/shared/Footer';
import Navbar from '@/components/Navbar';

const TermsOfService = () => {
  return (
    <>
      <SEOHead
        title="Terms of Service | Codilla.ai"
        description="Read the terms and conditions for using Codilla.ai platform."
      />
      <div className="min-h-screen bg-background">
        <Navbar />
        <main className="container mx-auto px-4 py-12 max-w-4xl">
          <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
          <p className="text-muted-foreground mb-8">Last updated: December 3, 2024</p>

          <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8">
            <section>
              <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground">
                By accessing or using Codilla.ai ("Service"), operated by GANAKYS CODILLA APPS (OPC) 
                Private Limited ("Company", "we", "us"), you agree to be bound by these Terms of Service. 
                If you do not agree, please do not use our Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
              <p className="text-muted-foreground">
                Codilla.ai is an AI-powered platform that helps users validate business ideas, 
                generate product requirements, and accelerate software development through multiple 
                AI agents and structured workflows.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">3. User Accounts</h2>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>You must provide accurate and complete registration information</li>
                <li>You are responsible for maintaining the security of your account</li>
                <li>You must be at least 18 years old to use the Service</li>
                <li>One person may not maintain more than one account</li>
                <li>You are responsible for all activities under your account</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">4. Token System and Payments</h2>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>AI features require tokens which can be purchased through Razorpay</li>
                <li>Token prices are displayed in Indian Rupees (INR)</li>
                <li>Purchased tokens are non-refundable except as required by law</li>
                <li>Unused tokens do not expire</li>
                <li>We reserve the right to modify token pricing with notice</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">5. Acceptable Use</h2>
              <p className="text-muted-foreground">You agree NOT to:</p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2 mt-2">
                <li>Use the Service for any illegal purpose</li>
                <li>Attempt to gain unauthorized access to our systems</li>
                <li>Interfere with or disrupt the Service</li>
                <li>Upload malicious code or content</li>
                <li>Impersonate others or provide false information</li>
                <li>Use automated tools to access the Service without permission</li>
                <li>Resell or redistribute the Service without authorization</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">6. Intellectual Property</h2>
              <h3 className="text-xl font-medium mb-2">Our Content</h3>
              <p className="text-muted-foreground">
                The Service, including its design, features, and content, is owned by the Company 
                and protected by intellectual property laws.
              </p>
              
              <h3 className="text-xl font-medium mb-2 mt-4">Your Content</h3>
              <p className="text-muted-foreground">
                You retain ownership of content you create using the Service (ideas, projects, code). 
                You grant us a limited license to process and store your content to provide the Service.
              </p>
              
              <h3 className="text-xl font-medium mb-2 mt-4">AI-Generated Content</h3>
              <p className="text-muted-foreground">
                Content generated by our AI features is provided for your use. You are responsible 
                for reviewing and validating AI-generated content before use.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">7. Disclaimers</h2>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>The Service is provided "AS IS" without warranties of any kind</li>
                <li>AI-generated content may contain errors and should be verified</li>
                <li>We do not guarantee business success or outcomes</li>
                <li>We are not responsible for third-party services (GitHub, Razorpay)</li>
                <li>Service availability may vary; we do not guarantee uptime</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">8. Limitation of Liability</h2>
              <p className="text-muted-foreground">
                To the maximum extent permitted by law, the Company shall not be liable for any 
                indirect, incidental, special, consequential, or punitive damages, including loss 
                of profits, data, or business opportunities, arising from your use of the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">9. Indemnification</h2>
              <p className="text-muted-foreground">
                You agree to indemnify and hold harmless the Company from any claims, damages, 
                or expenses arising from your use of the Service or violation of these Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">10. Termination</h2>
              <p className="text-muted-foreground">
                We may suspend or terminate your account for violations of these Terms or for any 
                reason with notice. Upon termination, you may request export of your data within 
                30 days.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">11. Governing Law</h2>
              <p className="text-muted-foreground">
                These Terms are governed by the laws of India. Any disputes shall be subject to 
                the exclusive jurisdiction of courts in Thiruvananthapuram, Kerala, India.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">12. Changes to Terms</h2>
              <p className="text-muted-foreground">
                We may modify these Terms at any time. Continued use of the Service after changes 
                constitutes acceptance of the new Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">13. Contact</h2>
              <p className="text-muted-foreground">
                For questions about these Terms, contact us at:
              </p>
              <address className="text-muted-foreground mt-2 not-italic">
                Email: <a href="mailto:legal@codilla.ai" className="text-primary hover:underline">legal@codilla.ai</a>
              </address>
            </section>
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
};

export default TermsOfService;
